name: Daily YouTube Scraper

on:
  schedule:
    - cron: '0 15 * * *'  # Runs daily at 3PM UTC (adjust as needed)
  workflow_dispatch:       # Allows you to run it manually too

# ✅ allow this workflow to push back to the repo
permissions:
  contents: write

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true   # ✅ keep GITHUB_TOKEN for push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install chromium

      - name: Decode creds.json from secret
        run: echo "${{ secrets.GOOGLE_CREDS_JSON_B64 }}" | base64 --decode > creds.json

      - name: Run scraper
        run: python scrape.py

      # ✅ NEW: commit keyword_index.txt if the script advanced it
      - name: Commit updated keyword index
        run: |
          if git diff --quiet --exit-code keyword_index.txt; then
            echo "No index changes to commit."
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add keyword_index.txt
            git commit -m "chore: advance keyword index [skip ci]"
            git push
          fi
